let div = document.createElement('div');
let textNode = document.createTextNode('Актеры American Horror Story 3 season "Coven" ');
document.body.append(div);
div.append(textNode);
let joke1 = document.createElement('joke1');
let j1 = document.createTextNode(' 1. Sarrah Polson ');
document.body.append(joke1);
joke1.append(j1);
let p = document.createElement('p');
let j2 = document.createTextNode(' 2. Evan Pitters');
document.body.append(p);
p.append(j2);
let p1 = document.createElement('p1');
let j3 = document.createTextNode(' 3 Emma Roberts and Jessica Lange');
document.body.append(p1);
p1.append(j3);
div.classList.add('title');
let title = document.querySelector('.title');
title.style.textAlign = "center";